### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by xiiliao8465** [alibaba-mmai-research/MoLo#6]
我用的ucf101数据集，跑的python runs/run.py --cfg configs/projects/MoLo/ucf101/MoLo_UCF101_1shot_v1.yaml
出现TypeError: string indices must be [integers这个报错
<img width="644" alt="6" src="https://github.com/user-attachments/assets/12120b8e-faad-4d8f-91c0-df50de03af9a">

**Comment by kktofcon** [comment]
请问你跑出代码来了没
